### ISSUE TITLE
Generate the release file

### ISSUE THREAD

**Issue by yharish991** [snowdrop/team#364]
A release.yml file should be generated for each release, this can be done by passing the values for the placeholders in release template file as parameters to the issues-manager, which would then generate the actual release.yml. To get the spring boot version we would have to parse the pom.xml

**Comment by yharish991** [comment]
My idea is to create a new command line command in `issues-manager` and pass the json blob something like below as an argument to generate the release.yaml file
```
{
  "version":"2.4.3",
  "jira":"ENTSBT-945",
  "release":"2021-06-30",
  "due":"2021-05-30",
  "sol":"2022-08-31",
  "components": [
    {
      "name": "Hibernate / Hibernate Validator / Undertow / RESTEasy",
      "jira": "EAPSUP-424"
    }, {
      "name": "Tomcat",
      "jira": "JWS-1982"
    }, {
      "name": "AMQP",
      "jira": "ENTMQCL-2589"
    }, {
      "name": "RESTEasy",
      "jira": "RESTEASY-2835"
    }, {
      "name": "OpenTracing / Jaeger",
      "jira": "ENTSBT-964",
      "product": "TRACING-1832",
    }, {
      "name": "Infinispan / DataGrid",
      "jira": "JDG-4363"
    }, {
      "name": "Narayana starter",
      "jira": "ENTSBT-965",
      "product": "JBTM-3431"
    }, {
      "name": "Vert.X starter",
      "jira": "ENTSBT-966",
      "product": "ENTVTX-669"
    }, {
      "name": "Spring Cloud Kubernetes",
      "jira": "ENTSBT-967"
    },{
      "name": "Dekorate",
      "jira": "ENTSBT-968"
    }
  ]
}
```

template yaml file would look something like this
```
project: ENTSBT
key: {{JIRA}}
version: {{VERSION}}
schedule:
  release: yyyy-mm-dd
  due: yyyy-mm-dd
  eol: yyyy-mm-dd
components:
- name: Hibernate / Hibernate Validator / Undertow / RESTEasy
  jira:
    project: EAPSUP
    key: {{HIBERNATE_JIRA}}
    issueTypeId: 10600
    assignee: ivassile
  properties:
  - hibernate
  - hibernate-validator
  - undertow
  - resteasy
- name: Tomcat
  jira:
    project: JWS
    key: {{TOMCAT_JIRA}}
    assignee: csutherl
  properties:
  - tomcat
- name: AMQP
  jira:
    project: ENTMQCL
    key: {{AMQP_JIRA}}
    assignee: justi9
  properties:
  - amqp-10-starter
- name: RESTEasy
  jira:
    project: RESTEASY
    key: {{RESTEASY_JIRA}}
    assignee: weinanli
  properties:
  - resteasy-spring-boot-starter
- name: OpenTracing / Jaeger
  jira:
    project: ENTSBT
    key: {{OPENTRACING_JIRA}}
    assignee: gandrian
  product:
    project: TRACING
    key: {{TRACING_JIRA}}
    assignee: objectiser
  properties:
  - opentracing-spring-jaeger-web-starter
- name: Infinispan / DataGrid
  jira:
    project: JDG
    key: {{INFINISPAN_JIRA}}
    assignee: nadirx
  properties:
  - infinispan
  - infinispan-starter
- name: Narayana starter
  jira:
    project: ENTSBT
    key: {{NARAYANA_JIRA}}
    assignee: gytis
  product:
    project: JBTM
    key: {{JBTM_JIRA}}
    assignee: mmusgrov
  properties:
  - narayana-starter
- name: Vert.X starter
  jira:
    project: ENTSBT
    key: {{VERTX_JIRA}}
    assignee: gytis
  product:
    project: ENTVTX
    key: {{ENTVTX_JIRA}}
    assignee: rruss
  properties:
  - vertx-spring-boot
- name: Spring Cloud Kubernetes
  jira:
    project: ENTSBT
    key: {{SCK_JIRA}}
    assignee: iocanel
  properties:
  - spring-cloud-kubernetes
- name: Dekorate
  jira:
    project: ENTSBT
    key: {{DEKORATE_JIRA}}
    assignee: iocanel
  properties:
  - dekorate

```
what do you think @metacosm @jacobdotcosta
