### ISSUE TITLE
Fix jdbc url in postgres bindings processor in spring-cloud-bindings

### ISSUE THREAD

**Issue by yharish991** [snowdrop/team#414]
PR https://github.com/spring-cloud/spring-cloud-bindings/pull/53

**Comment by yharish991** [comment]
PR has been merged in the `spring-cloud-bindings` library, so closing this issue

**Comment by cmoulliard** [comment]
Do you plan to create an example that we could use use to showcase how to bind a service using sprong boot and service binding operator ? @yharish991

**Comment by yharish991** [comment]
If you want me to demo the example i can, i added the link to the demo in the technical document too, pasting the link to the demo code here again https://github.com/yharish991/sample-service-binding-postgresql/tree/serviceBinding

**Comment by cmoulliard** [comment]
I'm thinking about having a new example or extending the DB example - https://github.com/snowdrop/crud-example in order to bind it using the `Service Binding Operator` and documenting it downstream on the customer portal under Snowdrop runtime documentation

**Comment by yharish991** [comment]
right now for the example i wrote i did some hacky stuff, because we don't have any operator yet(at least from my knowledge) that is spec compliant,so in order to generate the binding information that is understandable by the `spring-cloud-bindings` i used the mappings feature of service binding operator

```
mappings:
    - name: host
      value: '{{ .postgresDB.status.dbConnectionIP }}'
    - name: port
      value: '{{ .postgresDB.status.dbConnectionPort }}'
    - name: database
      value: '{{ .postgresDB.status.dbName}}'
    - name: username
      value: '{{ .postgresDB.status.dbCredentials.user }}'
    - name: password
      value: '{{ .postgresDB.status.dbCredentials.password }}'
    - name: type
      value: postgresql
```
If this new example is for customer portal, i think we should wait until we have an operator that is spec compliant in order to not confuse the customers
