### ISSUE TITLE
Admission Webhooks Java DevEx

### ISSUE THREAD

**Issue by csviri** [snowdrop/team#701]
## User Story
User story: As a developer I would like to create and deploy and test an admission web-hook easily as possible. So I don't spend to much time on other aspects then my business logic inside the web-hook.

## Details

Although [Admission controllers](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/) are basically HTTP Endpoints, it could be quite time consuming to setup one from scratch from java. 
Started to prototype a microframework that would make it very easy to implement a mutation or a validation hook:
https://github.com/java-operator-sdk/admission-controller-framework

See the definition of a mutation and a validation service, that is then just exposed by an endpoint:

https://github.com/java-operator-sdk/admission-controller-framework/blob/92ebf64de9e5dede7bd5954c7eb165aa08398ab5/samples/quarkus/src/main/java/io/javaoperatorsdk/admissioncontroller/sample/quarkus/AdmissionControllerConfig.java#L16-L33

```java
  @Singleton
  @Named("mutatingController")
  public AdmissionController<Pod> mutatingController() {
    return new AdmissionController<>((resource, operation) -> {
      resource.getMetadata().getLabels().putIfAbsent(APP_NAME_LABEL_KEY, "mutation-test");
      return resource;
    });
  }


  @Singleton
  @Named("validatingController")
  public AdmissionController<Pod> validatingController() {
    return new AdmissionController<>((resource, operation) -> {
      if (resource.getMetadata().getLabels().get(APP_NAME_LABEL_KEY) == null) {
        throw new NotAllowedException("Missing label: " + APP_NAME_LABEL_KEY);
      }
    });
  }
```

(The validation part could be also improved, to have even nicer api)

An other side of the story of Admission Hook  is the Configuration:
```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "pod-policy.example.com"
webhooks:
- name: "pod-policy.example.com"
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    service:
      namespace: "example-namespace"
      name: "example-service"
    caBundle: "Ci0tLS0tQk...<`caBundle` is a PEM encoded CA bundle which will be used to validate the webhook's server certificate.>...tLS0K"
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 5
```
The generation of this configuration could be a nice task for **decorate**, like annoting the endpoints and generating the resources with dekorate (see `@MutatingWebhook`,  `@ValidatingWebhook` annotations):

```
  @MutatingWebhook
  @POST
  @Path("mutate")
  @Consumes(MediaType.APPLICATION_JSON)
  @Produces(MediaType.APPLICATION_JSON)
  public AdmissionReview mutate(AdmissionReview admissionReview) {
    return mutationController.handle(admissionReview);
  }

  @ValidatingWebhook(useCertManager=true, operations={CREATE, UPDATE})
  @POST
  @Path("validate")
  @Consumes(MediaType.APPLICATION_JSON)
  @Produces(MediaType.APPLICATION_JSON)
  public AdmissionReview hello(AdmissionReview admissionReview) {
    return validationController.handle(admissionReview);
  }
```

One interesting part would be to generate the required certificate, but also support cert-manager as an alternative. But other several options for configurations are possible.

## Summary

So in summary, to get this work, and able to bootstrap a project, implement a webhook, and deploy it to Kubernetes in no time we need:

1. A Framework that encapsulates the common patters of admission and validation webhooks. Note that this a very thin layer (actually was hesitating if something like this is needed, but for now looks nice, and simple)
2. A generator that generates the project skeleton (maven archetype, cli  or other? ) - this part missing
3. Generate Related Kubernetes Resources Using Dekorate (or Quarkus extension)
  3.1 Deployment, Service 
  3.2 WebhookConfiguration
